version: "3.8"

services:
  app:
    build:
      args:
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /home/user/brain-decoding-cookbook
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
