version: "3.8"

services:
  app:
    build:
      args:
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /home/user/brain-decoding-cookbook
    working_dir: /home/user/brain-decoding-cookbook/reconstruction
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  torch171:
    build:
      args:
        - IMAGETAG=1.7.1-cuda11.0-cudnn8-runtime
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /home/user/brain-decoding-cookbook
    working_dir: /home/user/brain-decoding-cookbook/reconstruction
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
